services:
  postgres_db:
    container_name: SummerGreen
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: SummerGreen
    volumes:
      - D:/smg:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - Summer-Green

  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - D:/pgadmin:/var/lib/pgadmin
    ports:
      - "5055:80"
    networks:
      - Summer-Green



networks:
  Summer-Green:
    driver: bridge